### ISSUE TITLE
Microsoft.Sql/server resources no longer explorable

### ISSUE THREAD

**Issue by johnthcall** [projectkudu/AzureResourceExplorer#151]
![image](https://user-images.githubusercontent.com/23224070/27404777-200fe900-5684-11e7-8f15-630d4102ae48.png)

As seen in the attached picture when expanding Microsoft.Sql/servers no servers appear. I am able to search for sql and when selecting it expands to Microsoft.Sql/servers and is unable to expand further.

**Comment by davidebbo** [comment]
Indeed, that seems to have been regressed. @bala16 is investigating. ANd hopefully once it's fixed, it will work better than before, as it will include more metadata about the SQL provider.

**Comment by bala16** [comment]
should be fixed now.. @johnthcall can you verify? Thanks..

**Comment by johnthcall** [comment]
This appears fixed on my end, thanks for the quick turnaround!

**Comment by davidebbo** [comment]
@johnthcall I'm curious if you notice any difference from before. You should be seeing more sub nodes under the server compared to before, and we now use the richer swagger spec (from https://github.com/Azure/azure-rest-api-specs/tree/master/arm-sql).
