### ISSUE TITLE
Actions and Create tabs are greyed out

### ISSUE THREAD

**Issue by midimancoder** [projectkudu/AzureResourceExplorer#153]
Hi, please can you tell me why my actions and create tabs are greyed out? 

I have it on Read/Write and am logged in with my subscription account admin. 

Thanks

**Comment by davidebbo** [comment]
@midimancoder can you provide more details? What kind of resources are you trying to use this one? e.g. what does the full resource ID look like?

**Comment by midimancoder** [comment]
Hi, I am trying to learn how to use this tool and I just watched one of your videos. 

But my options to create are all greyed out. 

Please see this example 

![ddd](https://user-images.githubusercontent.com/26660794/27606666-0ef411a6-5b79-11e7-8b53-bd59977823ec.jpg)

**Comment by davidebbo** [comment]
It's important to talk about specific scenarios here. It seems you are trying to use that with `microsoft.compute/disks`?

As a test, does it work if you try on `Microsoft.Web/sites`?

**Comment by davidebbo** [comment]
Note that there is one known limitation: in order to create a resource of a given type, you need to already have at least one resource of that type in your subscriptions.

**Comment by davidebbo** [comment]
Oh, I see the problem. You need to look for those things under a specific **resource group**, and not under the 'providers' node that's directly under a subscription.

**Comment by midimancoder** [comment]
Hi David, 

Yes it appears that the resources have to exist and be present within a RG.

**Comment by davidebbo** [comment]
No, they don't necessarily have to exist with the specific RG. They can exist anywhere in your subs. But you need to use the API tree that's inside a RG. That's just the way the ARM API works, and is not specific to this tool.
