### ISSUE TITLE
AOBO for resources.azure.com

### ISSUE THREAD

**Issue by lmotto** [projectkudu/AzureResourceExplorer#155]
Is this on the road map?  Auth on behalf of works for portal.azure.com and sometimes, services that are still in preview require resources.azure.com or powershell to configure.  Would be nice to have this.  Thank you.

**Comment by davidebbo** [comment]
I'm not familiar with this. Can you please give more details about the scenario you're referring to?

**Comment by lmotto** [comment]
AOBO allows us to use federated logins to access the azure portal of our clients Azure subscriptions.  (These are CSP tenants.)  So, the process would be portal.azure.com/<tenant>.onmicrosoft.com > enter CSP azure ad username > redirected to ad fs login > enter ad ds password > login to <tenant> subscription complete.  If you were to try the same process without "/<tenant>.onmicrosoft.com", it would attempt to login as <username>@<csp tenant ad> which doesn't have access to CSP tenant because it's a different azure ad.  I hope I explained this correctly and that you followed.

Here's more info:
https://www.microsoft.com/en-us/download/details.aspx?id=50803
https://channel9.msdn.com/Series/cspdev/Module-11-Admin-On-Behalf-Of-AOBO

**Comment by davidebbo** [comment]
I see. My guess is that the auth mechanism used for Resource Explorer doesn't support this, and I'm not sure how easy that would be to add. @suwatch may have more comments.

**Comment by suwatch** [comment]
Please try `https://resources.azure.com/@tenantId`.    The `tenantId` is the tenant id and must be in guid form (we don't support canonical name).   Let us know,

**Comment by lmotto** [comment]
Thank you, this appears to work just fine.
