### ISSUE TITLE
Regression: 'deployments' are no longer available

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/AzureResourceExplorer#158]
The 'deployments' node is still there, but it says 'no GET Url' when clicking on it:

![image](https://user-images.githubusercontent.com/556238/27744638-242bd394-5d75-11e7-8106-8d53073e1ba4.png)

Note that this used to be hard coded as a special node before. Maybe it got lost in the recent re-architecture?

**Comment by bala16** [comment]
Deployments can be found under providers/Microsoft.Resources. 
This is a new node which we didn't have before, To avoid confusion will remove operations with no actions which should prevent this additional node from showing up.

Fixed by 105f925e2c3dfdcfdf23cacc62e8bbf52bfdb1c7

**Comment by davidebbo** [comment]
I confirmed that it's gone.
