### ISSUE TITLE
Accessing from IE11 shows blank page.

### ISSUE THREAD

**Issue by shinjisgogo** [projectkudu/AzureResourceExplorer#162]
Accessing from IE11 shows blank page. The issue can repro at any IE11. I don't remember clearly but I think "Azure Resource Explorer" support IE11. Correct? If it's supported, could you please look into this issue?

**Comment by ahmelsayed** [comment]
we're targetting [ES6](https://github.com/projectkudu/AzureResourceExplorer/blob/master/ARMExplorer.csproj#L36), so IE won't work

**Comment by davidebbo** [comment]
Let's use this issue to track that we need to detect IE and show a message that clearly indicates that it's not supported.

**Comment by davidebbo** [comment]
And to answer the first question, it did use to be supported indeed, but support was recently removed.

**Comment by gutzeit1106** [comment]
Can I ask a question for this issue? 

Do you have the recommended browser to use “https://resources.azure.com/”? If there is supported browser list, I’d like to know the information.

**Comment by bala16** [comment]
@gutzeit1106 any desktop browser with es6 support as listed in https://kangax.github.io/compat-table/es6/ can be used. (Google chrome, Microsoft Edge, Mozilla Firefox , Safari)

**Comment by bala16** [comment]
fixed in ec5249f39a2d3b50068707fe377cbdbd17a78611
