### ISSUE TITLE
Can't see tenant full name

### ISSUE THREAD

**Issue by DeLeneMirouze** [projectkudu/AzureResourceExplorer#165]
When I run the application locally I get GUID instead tenant name. But your deployed version works fine.

The source code show this:

 value["DisplayName"] = tenant["tenantId"];
value["DomainName"] = tenant["tenantId"];
value["TenantId"] = tenant["tenantId"];

How these line of code can display the right result?
thanks?

**Comment by bala16** [comment]
@DeLeneMirouze that is expected. We handle tenant list differently on localhost vs azure web app. You can find the relevant code at https://github.com/projectkudu/AzureResourceExplorer/blob/master/Controllers/ARMController.cs#L132
