### ISSUE TITLE
Missing AutoScale settings

### ISSUE THREAD

**Issue by ca-thompson** [projectkudu/AzureResourceExplorer#171]
When trying to view ScaleSet autoscale settings under Microsoft.Insights, No autoscale settings are displayed and a "No GET Url" message is returned.

**Comment by davidebbo** [comment]
Yep, known issue. It's fixed in staging site: https://resources-staging.azure.com. It will swap to prod later, but you can use it there for now.

**Comment by bala16** [comment]
I think there might also be another issue here. the latest swagger doesn't have any operations under microsoft.insights/autoscalesettings. but it seems 2015-04-01 might have them. I will see if we can add those older specs also.

**Comment by bala16** [comment]
Fixed by 66e9edfdba8ce4bb2c0e8bdc86e2e26d4e611ee8
