### ISSUE TITLE
Virtual Network Gateways & Connections are missing

### ISSUE THREAD

**Issue by lesterw1** [projectkudu/AzureResourceExplorer#173]
Please add support for Virtual Network Gateways (Microsoft.Network/virtualNetworkGateways) and Connections (Microsoft.Network/connections). Sadly, these resources do not appear in the explorer. I'm surprised that the underlying implementation doesn't enumerate all the resource types by doing the equivalent of (Get-AzureProvider).ResourceTypes.

**Comment by bala16** [comment]
![image](https://user-images.githubusercontent.com/28721598/29887222-9024633c-8d71-11e7-9d4b-493d95633fd2.png)

VirtualNetworkGateways should work in resource explorer. I just tested it on one of my resource groups. Connections should also work.
Can you make sure you are expanding the nodes under subscriptions/ your-subscriptionid /resourcegroups / your-resourcegroup / providers / Microsoft.network and not the one under subscriptions / your-subscriptionid / providers / Microsoft.Network.
Also if you know the name of your gateway you can search for it using the search box.

**Comment by lesterw1** [comment]
Ahh... I should have been more clear.  They do not show up under Subscription > Providers > Microsoft.Network (unlike other resources).  They DO show up when navigating via Resource Groups as you  have shown. Thank you for pointing out the work-around.
