### ISSUE TITLE
Resource Explorer is not showing Resource Providers including Microsoft.Web.

### ISSUE THREAD

**Issue by FinVamp1** [projectkudu/AzureResourceExplorer#176]
The customer has a lot of Resources in their subscription and the call to resources.azure.com/api/operations/providers/<subId> returns a lot of resource groups and their related providers. The ARM call does return a Skip token which may mean not all resource groups are returned. E.G management.azure.com:24582/subscriptions/<subId>/resources?%24expand=createdTime%2cchangedTime&%24skiptoken

**Comment by bala16** [comment]
Yes, this is a limitation with resource explorer currently. we don't walk the complete tree using skip token. Will use this issue to track this feature.

**Comment by bala16** [comment]
@FinVamp1 I made a fix to address some of the issues around skiptoken. Can you try it out at https://resources-staging.azure.com/ and i will push to prod site if there are no issues.

**Comment by bala16** [comment]
fixed by 526106d2690bfadee6125a9e5c9b36ac1381d485
