### ISSUE TITLE
Changes to service fabric not saving

### ISSUE THREAD

**Issue by ankurkapoor** [projectkudu/AzureResourceExplorer#181]
Hi,

When i am trying to save changes (adding a new property under FabricSettings section using the PUT operation, the screen refreshes and a GREEN Tick mark appears on the screen. However after refresh, the old property comes back again. I am basically trying to add new property but it never stays after refresh:

	{
        "name": "ClusterManager",
        "parameters": [
          {
            "name": "EnableDefaultServicesUpgrade",
            "value": "true"
          }
        ]
	}
![image](https://user-images.githubusercontent.com/9979266/33343841-b410e046-d47e-11e7-9d0c-714053cb9500.png)

**Comment by bala16** [comment]
The update is asynchronous. the operation returns 202 Accepted immediately on receiving the request but doesn't update the cluster at that point. After a while you should see the settings updated and reflected on Resource Explorer. 
You can also verify that the request was received by the cluster in the Activity log tab for your cluster in the portal.
