### ISSUE TITLE
Usages of Microsoft.Web/sites show currentValue 0 for all metric exept FileSystemStorage

### ISSUE THREAD

**Issue by mika1111** [projectkudu/AzureResourceExplorer#184]
While websites is running and metrics per instace show not 0 values in resource explorer it is always 0 for CpuTime, CpuTimeShortPeriod, BytesReceived, BytesSent, LocalBytesRead, LocalBytesWritten, MaxMemoryWorkingSetShortPeriod, NetworkBytesRead, NetworkBytesWritten, WPStopRequests

**Comment by davidebbo** [comment]
Unlikely to be a resource explorer issue, unless you don't seen that behavior when you call ARM directly.
