### ISSUE TITLE
https://resources.azure.com/ uses old api-version for Microsoft.Network

### ISSUE THREAD

**Issue by axelgMS** [projectkudu/AzureResourceExplorer#186]
https://resources.azure.com/ uses old api-version for Microsoft.Network

See attached screenshots.
Microsoft.Network is using api-version=2017-03-01 in Resource Explorer.
That prevents from using the latest features like the ones provided by api-version=2018-01-01 - like PickHostNameFromBackendAddress.

How can I select the latest api-version?
Can we give Resource Explorer the ability to choose that api-version?

thanks,

![1](https://user-images.githubusercontent.com/10450400/36839312-0c03a8fe-1d42-11e8-8c8f-4d6e99c0f026.jpg)
![2](https://user-images.githubusercontent.com/10450400/36839313-0c276a28-1d42-11e8-9ec2-a46bfd49055d.jpg)

**Comment by davidebbo** [comment]
It only supports one version. Normally, updates are driven by the RP team (e.g. Network team in this case), based on [this process](https://github.com/projectkudu/AzureResourceExplorer#adding-swagger-specs).

**Comment by bala16** [comment]
In the mean time https://resources.azure.com/raw/  will let you pick any apiversion if you know what json to post.

**Comment by davidebbo** [comment]
I've updated to the latest spec from https://github.com/Azure/azure-rest-api-specs/tree/master/specification/network/resource-manager/Microsoft.Network/stable/2018-01-01.

@axelgMS can you try https://resources-staging.azure.com/ and verify that it has the new APIs?

**Comment by bala16** [comment]
verified the version used for Microsoft.Network/applicationGateways is 2018-01-01. Closing this issue.
