### ISSUE TITLE
Using "Edit" to add property is not working 

### ISSUE THREAD

**Issue by thweid** [projectkudu/AzureResourceExplorer#187]
I am attempting to add a new property to my Service Fabric cluster. I go to https://resources.azure.com/subscriptions/_subscriptionid_/resourceGroups/_resourcegroupname_/providers/Microsoft.ServiceFabric/clusters/_clustername_. I can successfully press "Edit" and get the option to use "PATCH" or "PUT". After updating the fabricSettings portion to have a new property (ClusterManager) clicking either, a green check in a box will appear in the middle of the screen. 
![resourceexplorersucceed](https://user-images.githubusercontent.com/24856855/37738679-f2ac2a9c-2d14-11e8-8196-93c252c97588.PNG)
However, after several hours and multiple attempts, my change is still not appearing. How can I get my edit to successfully propagate to the service fabric cluster settings?

**Comment by bala16** [comment]
Check out https://github.com/projectkudu/AzureResourceExplorer/issues/181
