### ISSUE TITLE
I can only view, no edit button and cannot make updates!

### ISSUE THREAD

**Issue by georgerobinson** [projectkudu/AzureResourceExplorer#189]
So i'm playing around with the https://resources.azure.com/

I've clicked the read/write button but everything remains disabled.  All of the examples/videos show an edit button but mine just shows get.  The post button and create button are disabled.

Has this been discontinued?  Or does some setting need to be enabled in my Azure Subscription for it to work?

**Comment by davidebbo** [comment]
Can you be more specific what kind of resource you're trying that on? Please provide the full path (you can replace your resource names with tokens).

**Comment by georgerobinson** [comment]
I'm not sure what you mean when you say what resource am I trying it on.  If you mean particular api calls then all of them, everything i click on is disabled.

![untitled](https://user-images.githubusercontent.com/26631886/38576512-4347f7ba-3cf6-11e8-9867-bfb884b49231.png)


I've logged in my azure portal and then browse https://resources.azure.com/ I can click away and see all of the information.

**Comment by davidebbo** [comment]
You need to look under Resource Groups and find your resource there.

**Comment by georgerobinson** [comment]
Is this what you mean?

![untitled](https://user-images.githubusercontent.com/26631886/38576736-e1d35212-3cf6-11e8-996a-7015443673fc.png)

**Comment by davidebbo** [comment]
Yes, expand that and find the relevant resource in there. Or search for it by name in the Search box at the top.

**Comment by georgerobinson** [comment]
Arrghh, found it apologies.

**Comment by davidebbo** [comment]
np, it can be confusing in the tree UI. :)

**Comment by georgerobinson** [comment]
Yeah, I hadn't used it before and couldn't work out what was editable and what wasn't.
