### ISSUE TITLE
400 error when viewing sql resources

### ISSUE THREAD

**Issue by JonasSamuelsson** [projectkudu/AzureResourceExplorer#190]
Hi,
I'm unable to view any type of sql resource, get a 400 error back
```
{
  "data": {
    "code": "BadRequest",
    "message": "Invalid value for header 'x-ms-request-id'. The header must contain a single valid GUID.",
    "target": null,
    "details": [],
    "innererror": []
  },
  "status": 400
}
```

**Comment by bala16** [comment]
@JonasSamuelsson Can you provide more details on what API you are calling?

**Comment by davidebbo** [comment]
I see the same when directly requesting 

    GET https://management.azure.com/subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Sql/servers/{server}/databases?api-version=2015-05-01-preview

So that does not look Resource Explorer related, but more something to do with this particular API. Probably best to bring up on a SQL forum.

**Comment by davidebbo** [comment]
If instead using `api-version=2017-10-01-preview`, it works fine. So @bala16, we probably just need to update the swagger for SQL.

**Comment by bala16** [comment]
yes. looks like its a problem with an older api version. will update this..

**Comment by bala16** [comment]
updated the api version to 2017-10-01-preview. @JonasSamuelsson the sql apis should work now.

**Comment by JonasSamuelsson** [comment]
thanks 😃
