### ISSUE TITLE
resources.azure.com advertises non-working Azure CLI commands

### ISSUE THREAD

**Issue by twitchax** [projectkudu/AzureResourceExplorer#191]
Azure/azure-cli#6475 was filed against Azure CLI after customer came from https://resources.azure.com/, and the site is advertising bad commands.

**Comment by davidebbo** [comment]
Copying from that issue, error is:

```
$ az resource show --id /subscriptions/deadbeaf-1111-2222-3333-666666666666/resources --api-version 2017-05-10
az resource: error: argument --ids: invalid ResourceId value: '/subscriptions/deadbeef-1111-2222-3333-666666666666/resources'
```

It's not clear from that thread what should be the command. From an ARM standpoint, doing a GET on `/subscriptions/{sub}/resources?api-version=2017-05-10` is perfectly valid.

**Comment by tjprescott** [comment]
Another example it advertises is:
`az resource create --id /subscriptions/{sub}/resourceGroups/{group}/providers/Microsoft.Web/certificates --api-version 2016-03-01 --properties {}`

This seems to be the pattern in resource explorer for creates. Problem is, this does not work in CLI either.

I think the main problem is that the Resource Explorer is advertising commands it thinks should work, vice commands that actually do work. It makes assumptions that the CLI commands are just a thin wrapper around the API, which is sometimes the case, but often not.

**Comment by tjprescott** [comment]
cc/ @williexu, @johanste

**Comment by davidebbo** [comment]
I believe this worked at the time, but az probably changed. For any command that doesn't work, please provide details on what the correct command is.

**Comment by williexu** [comment]
@davidebbo for any endpoint used to **"list"** resources, (this also includes examples such as `/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/wilxgroup1/providers/Microsoft.Storage/storageAccounts`, there is no equivalent **"create"** command; how would that even work?

For the `resource show` examples, in the CLI, we use distinct list commands, i.e. `az resource list` and `az storage account list` to query the examples we've mentioned.

It is possible there is an argument for allowing use of `resource show` to accept any endpoint that one can do a GET on. Personally, however, I would think that this case should only be expected to work when passed a specific ARM resource ID, not endpoints for listing.

**Comment by davidebbo** [comment]
@williexu you're right, that create command is clearly bogus.

@bala16 it might be best to yank the Azure CLI tab altogether since it looks to be in pretty bad shape, and we don't have any resources to fix it right now.

**Comment by bala16** [comment]
I removed the azure cli tab from staging site today https://resources-staging.azure.com/
Will update prod site also tomorrow after testing for a little bit.  Will look into how we can fix the commands to re-enable the tab later.
