### ISSUE TITLE
Old version for Microsoft.ContainerService API

### ISSUE THREAD

**Issue by dsalamancaMS** [projectkudu/AzureResourceExplorer#193]
Hi Guys,

I was trying to get the CNI for my current AKS cluster, but looks like in resource explorer you guys are using an old version of the API that doesnt return such info, I had to use postman instead in order to use the newer API, I don't know if you guys are planing on changing this but the current version is too old: 2017-08-31

Resource Explorer:
![image](https://user-images.githubusercontent.com/33235720/41382496-9dcb7b3e-6f29-11e8-8a71-031a3ea6e2ce.png)

My own query using API version 2018-03-31
![image](https://user-images.githubusercontent.com/33235720/41382545-d458c602-6f29-11e8-86b8-979e2ddcb08b.png)

**Comment by davidebbo** [comment]
Could you try on the staging site https://resources-staging.azure.com/? Does that have the correct version?

**Comment by dsalamancaMS** [comment]
@davidebbo Yup, that one has the 2018-03-31 version, thanks David!

**Comment by davidebbo** [comment]
Great, we'll swap it into Prod soon, and we'll then close the issue.

**Comment by bala16** [comment]
Now also available on the prod site.
