### ISSUE TITLE
PATCH support for Virtual Machines

### ISSUE THREAD

**Issue by jtuliani** [projectkudu/AzureResourceExplorer#198]
Virtual Machines support PATCH: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/update

However, when editing a VM in Resource Explorer, I only have the PUT option.

It would be great if Resource Explorer exposed PATCH for VMs.

**Comment by bala16** [comment]
I updated the api-version used by Microsoft.Compute. PATCH should be available now.

**Comment by jtuliani** [comment]
Yes, that is working! Thanks for the quick fix.
