### ISSUE TITLE
POST actions for VM Scale Sets

### ISSUE THREAD

**Issue by jtuliani** [projectkudu/AzureResourceExplorer#199]
VM Scale Sets support a number of POST actions.
However, these are not available in Resource Explorer.
They should be!

**Comment by bala16** [comment]
After the update to Microsoft.Compute's api-version , this should also be fixed. Could you check?

**Comment by jtuliani** [comment]
Nope, for me the 'Actions' tab still shows 'Delete' and nothing else.

**Comment by bala16** [comment]
There was a problem with case sensitive matching. This should be fixed now.

**Comment by jtuliani** [comment]
Awesome, that's much better :)
Thanks for the quick work!
