### ISSUE TITLE
API version for Traffic Manager profiles is out of date

### ISSUE THREAD

**Issue by jtuliani** [projectkudu/AzureResourceExplorer#211]
Latest API version for Microsoft.Network/TrafficManagerProfiles is 2018-08-01.

Resource Explorer is using 2017-05-01

Please can we have an update?

It would be nice to solve this issue systemically, somehow.

**Comment by balag0** [comment]
We never update api versions proactively. Fastest way to get it updated is to open a PR yourself. Instructions - https://github.com/projectkudu/AzureResourceExplorer#adding-swagger-specs

For open issues i try update once a month but sometimes it can take longer.

**Comment by balag0** [comment]
Regarding Microsoft.Network/TrafficManagerProfiles I will try get it in this week.

**Comment by balag0** [comment]
Updated. Available in the staging site now - https://resources-staging.azure.com/
