### ISSUE TITLE
Can't login to site

### ISSUE THREAD

**Issue by MisinformedDNA** [projectkudu/AzureResourceExplorer#216]
When I go to https://resources.azure.com/, I am presented with a Basic Auth dialog:

![image](https://user-images.githubusercontent.com/1784452/51497391-95f30400-1d88-11e9-8abb-8c3e9432ca5b.png)

I didn't want to, but I convinced myself to try entering my Org creds, but to no avail. What am I supposed to enter? Or do I have to run it locally?

**Comment by davidebbo** [comment]
That's not normal, and I'm not seeing this. Is this with Chrome? Have you tried from Incognito? It should redirect you to Microsoft Account login screen.

**Comment by MisinformedDNA** [comment]
Chrome works fine. I should have thought of that. The issue is occurring on the browser Brave, which is built on Chromium. It's likely their fault, so I'll follow up with them.

**Comment by MisinformedDNA** [comment]
Filed https://github.com/brave/brave-browser/issues/3036
