### ISSUE TITLE
Create Source Control with Registered App

### ISSUE THREAD

**Issue by Suamere** [projectkudu/AzureResourceExplorer#221]
If I use https://resources.azure.com I can navigate to:

{MySubscription} > resourceGroups > {Group} > providers > Microsoft.Web > sites > {TestSite} > sourcecontrols > web

At that point, I can test a PUT to:

https://management.azure.com/subscriptions/{MySubscription}/resourceGroups/{Group}/providers/Microsoft.Web/sites/{TestSite}/sourcecontrols/web?api-version=2018-02-01

With the JSON Body:

	{
	  "properties": {
		"repoUrl": "https://bitbucket.org/{TeamName}/{repository}",
		"branch": "master"
	  }
	}

This is Successful.  It is worth noting that the User Interface is using the Credentials I'm logged in with, which is a master user.

However, when I use Bearer Token authentication with an Azure AD Registered App, I receive the error 404-NotFound `Cannot find User with name 5lol843-ff32-etcetc...`

If this is impossible, then please tell me what is expected to generate an SSH token, I can create the BitBucket AccessKey myself, and please tell me how to apply that to my Web App.

I do see in KUDU that there is an .SSH folder generated with bitbucket and the access key.  But I don't know everything that's happening behind the scenes.  I don't mind taking the longer approach if Azure can't handle this PUT request with a Client user.

**Comment by balag0** [comment]
This sounds like a question for web apps and not resource explorer and someone there might be able to help you better.

The api to add the token is 
https://management.azure.com/providers/Microsoft.Web/sourcecontrols/Bitbucket?api-version=2018-02-01

After you add the token you can update the repo info using the site level api you tried.

As for generating the oauth token for bitbucket the details are documented here - https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html

If it works for you - Azure Portal handles generating the oauth token and linking to your user credentials through deployment center - https://docs.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment#deploy-continuously-from-bitbucket
