### ISSUE TITLE
cant issue put 

### ISSUE THREAD

**Issue by willbrim** [projectkudu/AzureResourceExplorer#227]
cant issue put to a resource in a subscription I own, dosent even tell me why.

**Comment by balag0** [comment]
What is the resource type. Do you have atleast one resource of that type already in any of your subscriptions.
Check if https://github.com/projectkudu/AzureResourceExplorer/issues/205 is a duplicate

**Comment by willbrim** [comment]
Hi I am just trying to edit/update information for my VM. I can view the information in the JSON but when I add the info I want to add and click “put” I just see a yellow caution sigh and nothing happens.

Best Regards,
Will

Azure Cloud Engineer
| Microsoft Corporation
| office: +1 (425) 704-8476
| working hours: Mon-Fri 9:00 am - 5:00 pm PST
[34AE394F]  [5FD9F35] Azure

**Comment by balag0** [comment]
Scroll to the bottom of the page and check if there are any errors displayed.

**Comment by balag0** [comment]
closing stale issue.
