### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by M0ns1gn0r** [projectkudu/AzureResourceExplorer#239]
I have noticed the apiVersions of some providers (e.g. `Microsoft.Cdn`) are greatly outdated.  There is also an year-old open request to update the version for Traffic Manager https://github.com/projectkudu/AzureResourceExplorer/issues/211.

Does this mean the project is not maintained anymore and the devs should resort to [the reference](https://docs.microsoft.com/en-gb/azure/templates/microsoft.cdn/allversions)?

**Comment by balag0** [comment]
Answer is No :) 
But updates can take longer. It is not the intent of this project to always be on the latest api version pro actively.

**Comment by M0ns1gn0r** [comment]
What's is the intent, I wonder :confused:
