### ISSUE TITLE
Unable to list the Azure subscriptions from the drop down menu. Please assist

### ISSUE THREAD

**Issue by srboin** [projectkudu/AzureResourceExplorer#243]
![capture](https://user-images.githubusercontent.com/57825367/70776617-9121af00-1da3-11ea-82aa-c2151a745f98.jpg)

**Comment by israels** [comment]
This is a repeat of the issue I reported #242.  It's the tenant drop down, not subscription list though.

**Comment by balag0** [comment]
Fixed by badfa358ffef7093325f5497624d93fb8d25cd87
