### ISSUE TITLE
Azure Data Explorer

### ISSUE THREAD

**Issue by Joehannus** [projectkudu/AzureResourceExplorer#251]
I can't find a Azure Data Explorer resource in Resource Explorer. The "namespace" Microsoft.Kusto is not available in the navigational tree.

I even tried adding the resource id after the root url. When you do that you shortly see a result, but rather quick you are redirected to the resource group the kusto cluster is in.

**Comment by balag0** [comment]
Fixed by 0affe87aa9e95f25790db89938659d2d7fe07b14
