### ISSUE TITLE
[Question] How will resources.azure.com be updated?

### ISSUE THREAD

**Issue by kheiakiyama** [projectkudu/AzureResourceExplorer#315]
I expected it to be deployed triggered by `master` branch update, but it is not correct.

Is there a way for us to know the release?
Is there a release cycle?

I could not find out in Readme.md .
I only know the site is on Azure App Service. It is deployed with `.deployment` .

**Comment by balag0** [comment]
Updating master branch will trigger deployment to https://resources-staging.azure.com/.
Deploying to resources.azure.com is manual and we do it once a month or as required.

**Comment by kheiakiyama** [comment]
I got it thanks!
