### ISSUE TITLE
Nodes on the left pane (Providers/Subscriptions) do not load

### ISSUE THREAD

**Issue by BhargaviAnnadevara-MSFT** [projectkudu/AzureResourceExplorer#325]
The left pane of Azure Resource Explorer does not load Providers/Subscriptions and is **blank** all the time as shown under:

![image](https://user-images.githubusercontent.com/44050820/133308697-f4e86808-cd0b-4fc0-9f31-ef87752a7609.png)

Navigating directly to the resource URL does not help either:
```
https://resources.azure.com/subscriptions/xx-xx/resourceGroups/xx-xx/providers/Microsoft.Web/sites
```
This is regardless of the browser used and signing out and back in multiple times, clearing cookies/cache etc. Please check and fix.

**Comment by balag0** [comment]
Left pane load time depends on the number of subscriptions and resources available to the account. There is some perf work to be done but in the meantime just waiting longer should load the page.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@balag0 Agree. I remember noting that nodes used to load up in a few minutes in the past. But the pane has been blank from around 3 hours now. That said, I also tried using my MSA to load resources from a VSE subcription and see the same behavior.

**Comment by balag0** [comment]
That doesn't sound like a perf issue but please try again now. We made some improvements today.

**Comment by BhargaviAnnadevara-MSFT** [comment]
> That doesn't sound like a perf issue but please try again now. We made some improvements today.

@balag0 Confirming I can see the nodes now. And also noticed significant improvements in load time as well. Thank you. :)
