### ISSUE TITLE
Azure Resource Explorer down? #81327

### ISSUE THREAD

**Issue by BhargaviAnnadevara-MSFT** [projectkudu/AzureResourceExplorer#327]
_Originally opened by @pettermoe95 with https://github.com/MicrosoftDocs/azure-docs/issues/81327_.
_Please mention @pettermoe95 for further responses or inquiries_.

---

I'm following this docs to add extra values to scope login parameter for my Azure App Service: https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-oauth-tokens#refresh-auth-tokens

When I go to resources.azure.com I get:
Error 403 - This web app is stopped.

![image](https://user-images.githubusercontent.com/69798757/134127807-0f907ce4-527f-4050-81e3-2bbc68e04eff.png)

I can't find any information about why it is stopped, if it has moved, or what is happening.

---

_https://github.com/MicrosoftDocs/azure-docs/issues/81327#issuecomment-923939315_

@BhargaviAnnadevara-MSFT Yes, I have tried from several different networks now, and with several browsers. Both from my phone and laptop. I am trying to access this web app from Norway, but I have not tried to open the web app on VPN from a different country. Is it possible that the server has been stopped from where I am trying to access it, and that you are accessing it from a different instance?

**Comment by balag0** [comment]
This is not supported on resource explorer.

**Comment by pettermoe95** [comment]
@balag0 What do you mean is not supported?

**Comment by balag0** [comment]
Sorry, should have clarified. The token refresh mechanism linked from the docs doesnt work here.

**Comment by pettermoe95** [comment]
@balag0 I'm not sure you're understanding my problem. I want to go to resources.azure.com to configure some settings, but I simply can't access resources.azure.com. What I linked from the doc has worked before for me, only problem now is that I can't access resources.azure.com, it gives me the 403 web app is stopped error.

**Comment by balag0** [comment]
Oh okay. Does https://resources-staging.azure.com/ work?

**Comment by pettermoe95** [comment]
@balag0 No, I still get the same error. Here is a screenshot from my phone.
![Screenshot_20210921-231806_Chrome](https://user-images.githubusercontent.com/69798757/134249165-5c896fe8-d072-4d85-a6a5-b4a6e3c29646.jpg)

**Comment by balag0** [comment]
Looks like you might be using conditional access (MCAS)
https://docs.microsoft.com/en-us/cloud-app-security/proxy-intro-aad

This is not supported yet. 
For now, if you can, please disable that MCAS proxy or use a different client.

Opened  https://github.com/projectkudu/AzureResourceExplorer/issues/328 for tracking.
Please follow that issue for updates.
