### ISSUE TITLE
Change Tenant/Directory Option Missing?

### ISSUE THREAD

**Issue by JoeEager-VUMC** [projectkudu/AzureResourceExplorer#333]
Where did the option to change directories go?

**Comment by balag0** [comment]
Found the issue. Working on deploying a fix. Will update here soon. Thanks.

**Comment by balag0** [comment]
Should be fixed now. Please verify. Thanks

**Comment by JoeEager-VUMC** [comment]
Fixed thanks!!

**Comment by IronSean** [comment]
@JoeEager-VUMC Where is this? I still don't see it.

**Comment by JoeEager-VUMC** [comment]
> @JoeEager-VUMC @balag0 Where is this? I still don't see it.

It's gone again.

**Comment by balag0** [comment]
cannot repro this myself. Lets continue the discussion at https://github.com/projectkudu/AzureResourceExplorer/issues/334
