### ISSUE TITLE
RE: Access to resources.azure.com was denied 403 Error

### ISSUE THREAD

**Issue by backbackforward** [projectkudu/AzureResourceExplorer#357]
Hello Team, 
I have a customer issue where they are unable to access resources.azure.com
They receive a 403 error message when trying to access. 
This seems to be the similar to the issue below: 
https://github.com/projectkudu/AzureResourceExplorer/issues/350
[](https://github.com/projectkudu/AzureResourceExplorer/issues/350)

Can you please advise or ping me on MSFT teams?

**Comment by wirelessy** [comment]
Can confirm, it seems to be related to guest users of a given tenant.
Does not happen to native users of the tenant.

Should it be relevant, our guests have user roles, wheres our native users are typically global admins.

**Comment by backbackforward** [comment]
> Can confirm, it seems to be related to guest users of a given tenant. Does not happen to native users of the tenant.
> 
> Should it be relevant, our guests have user roles, wheres our native users are typically global admins.

So are your guest users able to access resources.azure.com?

**Comment by wirelessy** [comment]
No. The 403 error happens as described, and as mentioned in #350. Only native users are able to access the app.

**Comment by SriniYalamati** [comment]
Same here, I have a customer issue, they also unable to access resource.azure.com because of 403
They are trying to access via Guest user account. Azure Portal is working fine.
Please help unblock this asap.

**Comment by gunsto** [comment]
Same problem here:
native tenant is fine, related "guest" tenants receive 403

**Comment by balag0** [comment]
Hi, Guest accounts are not a supported scenario currently.

**Comment by wirelessy** [comment]
That is sort of ridicoulus, considering we are paying an awful lot for Azure, and also this has been working for the past three years.

**Comment by gunsto** [comment]
How can this not be a supported scenario? In larger corporations you have primary tenants for storing users in AAD and secondary tenants for deploying resources. Then all users on those secondary tenants are "guest". For me this sounds like an excuse, because the implementation might be tricky or time-consuming.
Please reconsider to re-open this issue!
