### ISSUE TITLE
Doesn't work for StreamAnalytics

### ISSUE THREAD

**Issue by furmangg** [projectkudu/AzureResourceExplorer#51]
If I look under https://management.azure.com/subscriptions/MySubID/resourceGroups/StreamAnalytics-Default-Central-US and list providers I would expect to see Microsoft.StreamAnalytics. But it isn't listed. Any idea what's going on there? Can you test this on your subscription after creating a Stream Analytics job? Is that because Stream Analytics is in public preview at this moment?

**Comment by ahmelsayed** [comment]
What is StreamAnalytics called in the portal? I am trying to test this with my subscription but I can't seem to find anything with that name in the portal.

**Comment by furmangg** [comment]
You have to sign up for the public preview. It is called Stream Analytics. Microsoft.StreamAnalytics in resource manager. 



On Apr 11, 2015, at 2:38 PM, Ahmed ElSayed <notifications@github.com> wrote:

What is StreamAnalytics called in the portal? I am trying to test this with my subscription but I can't seem to find anything with that name in the portal.

**Comment by furmangg** [comment]
And you see Stream Analytics on the old portal only but if I'm not mistaken it is managed with the resource manager PowerShell. Hope that helps

**Comment by davidebbo** [comment]
Can you try using [ARMClient](http://blog.davidebbo.com/2015/01/azure-resource-manager-client.html) to see if you're able to access those resources via ARM? If so, then it may be a matter of adding the right metadata to Resource Explorer.

**Comment by furmangg** [comment]
Would it be the API-version that's to blame? This doc says we need 2015-03-01. Is that supported in ARMExplorer. It doesn't seem to be in ARMClient if I understood an error message. 

https://msdn.microsoft.com/en-us/library/azure/dn835033.aspx

**Comment by davidebbo** [comment]
What do you mean by "It doesn't seem to be in ARMClient if I understood an error message"? WIth ARMClient, you pass the version explicitly, so it can work with any versions. But if you find that you can't make it work even with ARMClient, then there is little hope of having Explorer support it.

**Comment by furmangg** [comment]
Oops. I should have used 2015-03-01-preview in ARMClient. Working now. How do I specify the api-version in ARMExplorer?

**Comment by davidebbo** [comment]
You won't be able to make it work on Resource Explorer without some server changes. But at least, the fact that you got it working with ARMClient shows that it has the potential to work :)

**Comment by bala16** [comment]
Fixed by 81aa9625d7fa7af5899b523e7b5bc72e922092ca
