### ISSUE TITLE
Add support for Service Bus and Event Hub

### ISSUE THREAD

**Issue by pawelpabich** [projectkudu/AzureResourceExplorer#60]
That would be great :)

**Comment by davidebbo** [comment]
In theory, ARMExplorer gives a default experience for all ARM resources. Not everything works, but they at least show up. Are you not seeing that for these providers?

**Comment by pawelpabich** [comment]
Nope, should I flip some kind of switch to see them?

![image](https://cloud.githubusercontent.com/assets/347637/8356421/8371929c-1b98-11e5-965d-0c5f0ffc2352.png)

I do have 2 Service Buses and 5 Event Hubs

![image](https://cloud.githubusercontent.com/assets/347637/8356504/206a480a-1b99-11e5-8cad-09c29c866558.png)

**Comment by davidebbo** [comment]
I think you may be looking directly under the subscription. You need to look under the specific resource group that they’re in.

**Comment by pawelpabich** [comment]
I looked there and the nodes are empty. Is it maybe because Serivce Bus is only available on the old portal where there are not resources groups?

![image](https://cloud.githubusercontent.com/assets/347637/8357299/96dbed96-1b9d-11e5-98ed-1b0eb0f69e88.png)

**Comment by davidebbo** [comment]
It's not so much about portal as about ARM API. ARMExplorer only supports resources that are exposed via ARM. It may indeed be that those aren't.

**Comment by pawelpabich** [comment]
Do you expect them to be exposed any time soon? I'm also interested in the HBase clusters.

**Comment by davidebbo** [comment]
Not sure, but I'd suggest asking on the various MSDN forums that target those resource types.

**Comment by davidebbo** [comment]
I just tried it, and was able to see my Service Bus there:

![image](https://cloud.githubusercontent.com/assets/556238/12251789/6b45bf46-b886-11e5-832d-a213573d5c5c.png)

Not sure if something changed. Note that without the metadata, we only get the basic support, but at least it does work.

**Comment by bala16** [comment]
Both eventhubs and and service bus are supported now.
