### ISSUE TITLE
Add support for Azure CLI

### ISSUE THREAD

**Issue by stuartleeks** [projectkudu/AzureResourceExplorer#99]
The details pane shows PowerShell cmdlet usage for exploring and manipulating resources. It would be great to have the same for CLI :-)

**Comment by davidebbo** [comment]
Yes. Right now it's hard because the xplat CLI doesn't have good support to make low level ARM requests.

**Comment by snobu** [comment]
Opened an issue to check what the **az** guys are up to -- https://github.com/Azure/azure-cli/issues/2921

**Comment by davidebbo** [comment]
Yep, I already discussed with them and they recently added it (not sure if released).

But I think they might still be missing the ability to POST to actions. Still, we could get this started.

**Comment by snobu** [comment]
Closing. Support for azure-cli (az) added in https://github.com/projectkudu/AzureResourceExplorer/commit/82c09909844903103e3a378827f4867f854e6864
